@echo off
echo Clearing stale git lock...
del /f ".git\index.lock" 2>nul
echo Staging files...
git add index.html roadmap.html
echo Committing...
git commit -m "Add roadmap page and nav links"
echo Pushing to origin...
git push
echo.
echo Done! Press any key to close.
pause
